import { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { ArrowLeft, MapPin, CreditCard, Banknote, QrCode, CheckCircle } from 'lucide-react';
import { z } from 'zod';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { useCart } from '@/contexts/CartContext';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import type { Store } from '@/types';

const addressSchema = z.object({
  address: z.string().trim().min(5, 'Endereço deve ter no mínimo 5 caracteres').max(200),
  city: z.string().trim().min(2, 'Cidade é obrigatória').max(100),
  state: z.string().trim().length(2, 'Use a sigla do estado (ex: SP)'),
  zip_code: z.string().trim().regex(/^\d{5}-?\d{3}$/, 'CEP inválido').optional().or(z.literal('')),
  notes: z.string().trim().max(500).optional(),
});

type AddressForm = z.infer<typeof addressSchema>;

const paymentMethods = [
  { id: 'pix', label: 'PIX', icon: QrCode, description: 'Pagamento instantâneo' },
  { id: 'credit', label: 'Cartão de Crédito', icon: CreditCard, description: 'Visa, Master, Elo' },
  { id: 'debit', label: 'Cartão de Débito', icon: CreditCard, description: 'Na entrega' },
  { id: 'cash', label: 'Dinheiro', icon: Banknote, description: 'Na entrega' },
];

export default function Checkout() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { items, subtotal, clearCart, currentStoreId } = useCart();
  const [store, setStore] = useState<Store | null>(null);
  const [paymentMethod, setPaymentMethod] = useState('pix');
  const [submitting, setSubmitting] = useState(false);
  const [orderSuccess, setOrderSuccess] = useState<string | null>(null);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<AddressForm>({
    resolver: zodResolver(addressSchema),
  });

  useEffect(() => {
    if (!user) {
      navigate('/auth');
      return;
    }

    if (items.length === 0) {
      navigate('/');
      return;
    }

    if (currentStoreId) {
      fetchStore();
    }
  }, [user, items.length, currentStoreId, navigate]);

  const fetchStore = async () => {
    if (!currentStoreId) return;

    const { data } = await supabase
      .from('stores')
      .select('*')
      .eq('id', currentStoreId)
      .single();

    if (data) {
      setStore(data as Store);
    }
  };

  const deliveryFee = store?.delivery_fee || 0;
  const total = subtotal + deliveryFee;

  const onSubmit = async (data: AddressForm) => {
    if (!user || !currentStoreId) return;

    setSubmitting(true);

    // Create order
    const { data: order, error: orderError } = await supabase
      .from('orders')
      .insert({
        customer_id: user.id,
        store_id: currentStoreId,
        order_number: '', // Will be generated by trigger
        subtotal,
        delivery_fee: deliveryFee,
        discount: 0,
        total,
        delivery_address: data.address,
        delivery_city: data.city,
        delivery_state: data.state.toUpperCase(),
        delivery_zip: data.zip_code || null,
        delivery_notes: data.notes || null,
        payment_method: paymentMethod,
        status: 'pending',
      })
      .select('id, order_number')
      .single();

    if (orderError) {
      console.error('Error creating order:', orderError);
      toast.error('Erro ao criar pedido');
      setSubmitting(false);
      return;
    }

    // Create order items
    const orderItems = items.map(item => ({
      order_id: order.id,
      product_id: item.product_id,
      product_name: item.product.name,
      product_image: item.product.image_url,
      quantity: item.quantity,
      unit_price: item.product.price,
      total_price: item.product.price * item.quantity,
    }));

    const { error: itemsError } = await supabase
      .from('order_items')
      .insert(orderItems);

    if (itemsError) {
      console.error('Error creating order items:', itemsError);
      toast.error('Erro ao adicionar itens ao pedido');
      setSubmitting(false);
      return;
    }

    // Clear cart and show success
    await clearCart();
    setOrderSuccess(order.order_number);
    setSubmitting(false);
  };

  if (!user || items.length === 0) {
    return null;
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-40 bg-card border-b border-border px-4 py-4">
        <div className="max-w-2xl mx-auto flex items-center gap-4">
          <Button variant="ghost" size="icon" onClick={() => navigate(-1)}>
            <ArrowLeft className="w-5 h-5" />
          </Button>
          <h1 className="text-xl font-semibold">Finalizar Pedido</h1>
        </div>
      </header>

      <main className="max-w-2xl mx-auto p-4 space-y-6">
        {/* Store Info */}
        {store && (
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                {store.logo_url ? (
                  <img src={store.logo_url} alt={store.name} className="w-12 h-12 rounded-lg object-cover" />
                ) : (
                  <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center">
                    <span className="text-lg font-bold text-primary">{store.name[0]}</span>
                  </div>
                )}
                <div>
                  <p className="font-medium">{store.name}</p>
                  <p className="text-sm text-muted-foreground">
                    Entrega em ~{store.avg_delivery_time} min
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Order Items Summary */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Resumo do Pedido</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            {items.map((item) => (
              <div key={item.id} className="flex justify-between text-sm">
                <span>{item.quantity}x {item.product.name}</span>
                <span>R$ {(item.product.price * item.quantity).toFixed(2)}</span>
              </div>
            ))}
            <div className="border-t pt-3 space-y-2">
              <div className="flex justify-between text-sm">
                <span>Subtotal</span>
                <span>R$ {subtotal.toFixed(2)}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span>Taxa de entrega</span>
                <span>R$ {deliveryFee.toFixed(2)}</span>
              </div>
              <div className="flex justify-between font-bold">
                <span>Total</span>
                <span>R$ {total.toFixed(2)}</span>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Delivery Address */}
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg flex items-center gap-2">
                <MapPin className="w-5 h-5" />
                Endereço de Entrega
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <Label htmlFor="address">Endereço completo *</Label>
                <Input
                  id="address"
                  placeholder="Rua, número, complemento"
                  {...register('address')}
                />
                {errors.address && (
                  <p className="text-sm text-destructive mt-1">{errors.address.message}</p>
                )}
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="city">Cidade *</Label>
                  <Input id="city" placeholder="Cidade" {...register('city')} />
                  {errors.city && (
                    <p className="text-sm text-destructive mt-1">{errors.city.message}</p>
                  )}
                </div>
                <div>
                  <Label htmlFor="state">Estado *</Label>
                  <Input id="state" placeholder="SP" maxLength={2} {...register('state')} />
                  {errors.state && (
                    <p className="text-sm text-destructive mt-1">{errors.state.message}</p>
                  )}
                </div>
              </div>

              <div>
                <Label htmlFor="zip_code">CEP</Label>
                <Input id="zip_code" placeholder="00000-000" {...register('zip_code')} />
                {errors.zip_code && (
                  <p className="text-sm text-destructive mt-1">{errors.zip_code.message}</p>
                )}
              </div>

              <div>
                <Label htmlFor="notes">Observações</Label>
                <Textarea
                  id="notes"
                  placeholder="Ex: Apartamento 12, bloco B, interfone 123"
                  {...register('notes')}
                />
              </div>
            </CardContent>
          </Card>

          {/* Payment Method */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg flex items-center gap-2">
                <CreditCard className="w-5 h-5" />
                Forma de Pagamento
              </CardTitle>
            </CardHeader>
            <CardContent>
              <RadioGroup value={paymentMethod} onValueChange={setPaymentMethod}>
                <div className="space-y-3">
                  {paymentMethods.map((method) => {
                    const Icon = method.icon;
                    return (
                      <label
                        key={method.id}
                        className={`flex items-center gap-4 p-4 rounded-lg border cursor-pointer transition-colors ${
                          paymentMethod === method.id
                            ? 'border-primary bg-primary/5'
                            : 'border-border hover:bg-muted'
                        }`}
                      >
                        <RadioGroupItem value={method.id} />
                        <Icon className="w-5 h-5 text-muted-foreground" />
                        <div className="flex-1">
                          <p className="font-medium">{method.label}</p>
                          <p className="text-sm text-muted-foreground">{method.description}</p>
                        </div>
                      </label>
                    );
                  })}
                </div>
              </RadioGroup>
            </CardContent>
          </Card>

          {/* Submit */}
          <Button type="submit" className="w-full" size="lg" disabled={submitting}>
            {submitting ? 'Processando...' : `Confirmar Pedido • R$ ${total.toFixed(2)}`}
          </Button>
        </form>
      </main>

      {/* Success Dialog */}
      <Dialog open={!!orderSuccess} onOpenChange={() => {}}>
        <DialogContent className="text-center">
          <DialogHeader>
            <DialogTitle className="sr-only">Pedido Realizado</DialogTitle>
          </DialogHeader>
          <div className="py-6 space-y-4">
            <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto">
              <CheckCircle className="w-10 h-10 text-green-600" />
            </div>
            <div>
              <h2 className="text-2xl font-bold">Pedido Realizado!</h2>
              <p className="text-muted-foreground mt-2">
                Seu pedido #{orderSuccess} foi enviado para o estabelecimento.
              </p>
            </div>
            <div className="space-y-2 pt-4">
              <Button asChild className="w-full">
                <Link to="/orders">Ver Meus Pedidos</Link>
              </Button>
              <Button asChild variant="outline" className="w-full">
                <Link to="/">Continuar Comprando</Link>
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
